name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia 00:00 UTC
  workflow_dispatch:      # permite rodar manualmente
  push:
    branches: [ main ]    # também roda quando houver push na main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielPetinatti
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar animação no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
